version: '5.0.2'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb

  # mongo container
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - my-blog-db:/data/db

  # prometheus
  prom-server:
    image: prom/prometheus
    ports: 
      - "9090:9090"
    volumes:
      - "./prometheus-config.yml:/etc/prometheus/prometheus.yml"
    depends_on:
      - backend
volumes:
  my-blog-db:
